version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ai_chat
      MYSQL_USER: ai_chat
      MYSQL_PASSWORD: ai_chat
      MYSQL_ALLOW_EMPTY_PASSWORD : 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - ai-chat
  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - "8003:80"
      - "8443:443"
    networks:
      - ai-chat
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8002:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - ai-chat
volumes:
  persistent:
networks:
  ai-chat:
    driver: bridge
